<?php
/**
 * MIT License
 * Copyright (c) 2024 TopTechDial
 * 
 * High Volume Discovery Index - Cluster 2
 * Thousands of lines of curated enterprise metadata for search benchmarking
 */

const INDEX_CLUSTER_2 = [
    ['id' => 1001, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1002, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1003, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1004, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1005, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1006, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1007, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1008, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1009, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1010, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1011, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1012, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1013, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1014, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1015, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1016, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1017, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1018, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1019, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1020, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1021, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1022, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1023, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1024, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1025, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1026, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1027, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1028, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1029, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1030, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1031, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1032, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1033, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1034, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1035, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1036, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1037, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1038, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1039, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1040, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1041, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1042, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1043, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1044, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1045, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1046, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1047, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1048, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1049, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1050, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1051, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1052, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1053, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1054, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1055, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1056, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1057, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1058, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1059, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1060, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1061, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1062, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1063, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1064, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1065, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1066, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1067, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1068, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1069, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1070, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1071, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1072, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1073, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1074, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1075, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1076, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1077, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1078, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1079, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1080, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1081, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1082, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1083, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1084, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1085, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1086, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1087, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1088, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1089, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1090, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1091, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1092, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1093, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1094, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1095, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1096, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1097, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1098, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1099, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
    ['id' => 1100, 'city' => 'Mumbai', 'val' => 'Strategic technological infrastructure and software development for global enterprises.'],
];
?>
